//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Book
{
    public int BookID { get; set; }
    public string Title { get; set; }
    public int CategoryID { get; set; }
    public string ISBN { get; set; }
    public string Author { get; set; }
    public int Stock { get; set; }
    public decimal Price { get; set; }
    public Nullable<int> DiscountCode { get; set; }

    public virtual Category Category { get; set; }
    public virtual Discount Discount { get; set; }
}

public partial class Category
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Category()
    {
        this.Books = new HashSet<Book>();
    }

    public int CategoryID { get; set; }
    public string CategoryName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Book> Books { get; set; }
}

public partial class Discount
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Discount()
    {
        this.Books = new HashSet<Book>();
    }

    public int DiscountCode { get; set; }
    public Nullable<int> DiscountPercentage { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Book> Books { get; set; }
}

public partial class Order
{
    public int OrderID { get; set; }
    public Nullable<System.DateTime> OrderDate { get; set; }
    public string MailingAddress { get; set; }
    public Nullable<double> TotalPrice { get; set; }
    public Nullable<short> UserID { get; set; }
}

public partial class OrderDetail
{
    public int OrderID { get; set; }
    public short BookID { get; set; }
    public Nullable<short> Quantity { get; set; }
    public Nullable<double> UnitPrice { get; set; }
    public Nullable<double> SubtotalPrice { get; set; }
}
